### PR TITLE
Adding only pick option in 'sri_tiago_pick_and_place_simulation' and updating readme

### PR DESCRIPTION
**Pull request by DorianBordes**

### CODE REVIEW

**Review by faty001 — APPROVED** [review]

**Review by olivier-stasse — APPROVED** [review]
LGTM

**Review by olivier-stasse — APPROVED** [review]
LGTM

**Review by olivier-stasse — CHANGES_REQUESTED** [review]
Please remove pyc file and solve conflicts

**Comment by olivier-stasse** [comment]
Il faut enlever sri_tiago_pick/scripts/spherical_grasps_server.pyc et résoudre les conflits avec sri_tiago_pick_and_place_simulation/README.md

**Pull request closed without merging**
